### ISSUE TITLE
Error while compiling: multiple packages link to native library `vorbis`, but a native library can be linked only once

### ISSUE THREAD

**Issue by cotti** [CerulanLumina/azureost-core-rs#3]
Hello. While trying to compile Azureost's CLI, I have encountered this duplicate linking error. Seems like somewhere down the chain two different vorbis versions are required. I have checked out the core library repo to further isolate the issue, and it's occurring here too.

 `$ cargo build --release
    Updating crates.io index
error: multiple packages link to native library `vorbis`, but a native library can be linked only once

package `vorbis-sys v0.0.8`
    ... which is depended on by `vorbis v0.1.0`
    ... which is depended on by `azure-ost-core v0.1.11 (A:\home\Cotti\Dev\azureost-core-rs)`
links to native library `vorbis`

package `vorbis-sys v0.1.0`
    ... which is depended on by `vorbisfile-sys v0.0.8`
    ... which is depended on by `vorbis v0.1.0`
    ... which is depended on by `azure-ost-core v0.1.11 (A:\home\Cotti\Dev\azureost-core-rs)`
also links to native library `vorbis``

**Comment by LuminaSapphira** [comment]
Looks like the vorbis dependency is broken

**Comment by LuminaSapphira** [comment]
I removed Cargo.lock from .gitignore in 7d765c0 , which should fix it. Please note that this is a bunch of legacy code that I wrote while learning Rust for the first time :P 

I'm working on a rewrite of the whole library for interacting with the data files but I got sidetracked by school and health concerns, etc.
